name: terraform cicd test
# cicdを実行したブランチを指定
on:
  push:
    branches:
      - develop

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_NAME  }}
  TF_VERSION: 1.5.1
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION  }}

# AWS認証（OIDC）で必要な権限
permissions:
  id-token: write
  contents: read

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
      - uses: actions/checkout@v3

      # AWS認証（OIDC）
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      # Terraform準備
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      ### フォーマット修正箇所をチェック
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      # 初期化
      - name: Terraform init
        run: terraform init

      # dry run 実行
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # deploy 実行
      - name: Terraform apply
        run: terraform apply -auto-approve
